# Generated by Django 3.1.7 on 2021-03-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='codeArticle',
            new_name='code_article',
        ),
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='idPayment',
            new_name='id_payment',
        ),
    ]
