# Generated by Django 3.1.7 on 2021-03-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210313_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
