# Generated by Django 3.1.7 on 2021-03-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentdetail_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='code_article',
            new_name='id_article',
        ),
    ]
